### ISSUE TITLE
How to set this up for Windows?

### ISSUE THREAD

**Issue by chaoscreater** [filippofinke/WordGPT#4]
Hi there, could you please provide some basic instructions on how to set this up on Windows? I know how to install add-ins in Word, but not quite sure what to do it with your "manifest.xml" file here.

**Comment by filippofinke** [comment]
Follow this guide: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing

1. Create a Shared Folder
2. Copy the XML (https://word-gpt-filippofinke.vercel.app/manifest.xml)
3. Paste the XML inside the Shared Folder
4. Trust the folder
5. Go to your add-in

**Comment by chaoscreater** [comment]
Sorry, but the instructions don't make sense.

In the guide you have provided, if you search for "XML", it will take you to the section "Sideload an add-in on the web when using Visual Studio" and that's clearly not it.

I think the guide you are referring to is this one:
https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#manually-sideload-an-add-in-to-office-on-the-web

However, that one doesn't talk about creating any folder and trusting it.

Anyway, I followed the guide that I just linked and got it working. However, this is for Office in the web. What about Office for desktop? On the desktop version, there isn't an option to load the addin:

![image](https://user-images.githubusercontent.com/18227319/229047157-376e0283-725a-4de5-9e2a-1788b04b2494.png)

**Comment by chaoscreater** [comment]
Never mind, I got it working on the desktop as well. I see what you mean by creating a shared folder now. This is the guide that I used with more details:
https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md

For anyone following that guide, you can skip the registry part, as you can do it all in the Word app itself.

Then, go to Developer -> Add-ins -> Shared folder and add it there

![image](https://github.com/filippofinke/WordGPT/assets/18227319/ff19b586-50a1-455c-8a36-b3513cc1602f)
