### ISSUE TITLE
WINDOWS如何安装

### ISSUE THREAD

**Issue by shenlujing2022** [filippofinke/WordGPT#9]
How to install and use? Where is the installation method?

**Comment by filippofinke** [comment]
Hi, to sideload the add-in for office using Windows you can follow this guide:
https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

**Comment by Phakira79** [comment]
Phakira
